name: Terraform CI/CD

on:
  push:
    branches:
      - main  # Trigger workflow on push to the `main` branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:  # Define environment variables for the entire job
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-west-2 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform-eks  # Specify subdirectory

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform-eks

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve
        working-directory: ./terraform-eks
