name: Terraform CI/CD

on:
  push:
    branches:
      - main  # Run workflow on push to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest  # GitHub runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Check out your code to the runner

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Make sure the correct version is specified

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform-eks  # Tell Terraform to run in the `terraform-eks` directory

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform-eks  # Ensure it runs plan inside the `terraform-eks` directory

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve
        working-directory: ./terraform-eks
