name: CI/CD Test Workflow

on:
  push:
    branches:
      - main  # Runs the workflow on every push to the `main` branch

jobs:
  test-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Pulls your repo files into the runner

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Use the required Terraform version

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform-eks  # Initialize the Terraform working directory

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform-eks  # Validates .tf files without building anything

      - name: Terraform Plan (Dry Run)
        run: terraform plan
        working-directory: ./terraform-eks  # Dry run, shows plan without applying changes

      - name: Print Success Message
        run: echo "GitHub Actions workflow ran successfully without building any resources!"
