name: CI/CD Test Workflow

on:
  push:
    branches:
      - main  # Runs the workflow on every push to the `main` branch

jobs:
  test-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Hello Message
        run: echo "Hello from GitHub Actions!"

      - name: Display System Information
        run: |
          echo "Running on $(uname -a)"
          echo "Current working directory:"
          pwd

      - name: List Files in Terraform Directory
        run: ls -l ./terraform-eks  # Ensure that files are present

      - name: Run Terraform Validate
        run: terraform validate
        working-directory: ./terraform-eks  # Validates configuration files

      - name: Run Terraform Plan (Dry Run)
        run: terraform plan
        working-directory: ./terraform-eks  # Dry run without apply
